name: sysfoo-ci-pipeline
on: push
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Welcome to sysfoo"
      
      - name: Code checkout
        uses: actions/checkout@v6
      
      - name: Maven Test
        run: mvm test
      
      - name: Clean package
        run: mvn clean
      
      - name: Maven package
        run: mvn package

      - name: View files
        run: ls -lrt
  
