name: sysfoo-ci-pipeline
on: 
  push:
    branches:
      - 'master'
jobs:
  sysfoo-ci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Welcome to sysfoo"
      
      - name: Code checkout
        uses: actions/checkout@v6
      
      - name: Maven Test
        run: mvn test
      
      - name: Clean package
        run: mvn clean
      
      - name: Maven package
        run: mvn package

      - name: View files
        run: ls -lrt target

      - name: upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysfoo
          path: target/**.war
  
